# Generated by Django 3.0.2 on 2020-02-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200216_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='image_url',
        ),
    ]
